# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Weka for Processing
email: 
description: > # this means to ignore newlines until "baseurl:"
  A Library by [Rong-Hao Liang](mailto:r.liang@tue.nl), [Janet Huang](mailto:Y.C.Huang@tue.nl) and [Wesley Hartogs](https://wesleyhartogs.nl) for the [Processing](http://www.processing.org) programming environment.  
  
keywords: processing.org, library, Machine Learning, Weka, Data, classification, regression, neural networks"
baseurl: "/Weka4P" # the subpath of your site, e.g. /blog
url: "howieliang.github.io" # the base hostname & protocol for your site
github_username: HowieLiang 

# Build settings
markdown: kramdown

collections:
  documentation:
    output: true
    permalink: /documentation/:path/
